name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rustfmt:
    name: Check and Fix Rust Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true
      - name: Check Formatting
        run: rustfmt --edition 2021 --check $(find . -name '*.rs' -print) || true
      - name: Fix Formatting
        run: rustfmt --edition 2021 $(find . -name '*.rs' -print)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automatically format Rust code'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit_message: 'Fix Rust format'
          title: 'Fix Rust format'
          body: 'This is an auto-generated PR with Rust format fixes.'
          branch: 'format-fix'
          delete_branch_after_merge: true

  build-and-test:
    name: Build and Test
    needs: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
