name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rustfmt:
    name: Check and Fix Rust Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          token: ${{ secrets.TOKEN }}  
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Prepare Branch for Changes
        run: |
          git fetch origin main:temp-main --force
          git checkout -B format-fix temp-main
      - name: Check Formatting
        run: rustfmt --edition 2021 --check $(find . -name '*.rs' -print) || true
      - name: Fix Formatting
        run: rustfmt --edition 2021 $(find . -name '*.rs' -print)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automatically format Rust code'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          branch: format-fix  
      - name: Check and Fix Formatting
        run: |
            rustfmt --edition 2021 --check $(find . -name '*.rs' -print) || true
            rustfmt --edition 2021 $(find . -name '*.rs' -print)
      - name: Commit and Push Changes
        run: |
            git add -A
            git commit -m "Automatically format Rust code"
            git push --set-upstream origin format-fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
              token: ${{ secrets.GITHUB_TOKEN }}
              commit-message: 'Fix Rust formatting'
              title: 'Fix Rust formatting'
              body: 'This is an auto-generated PR with Rust formatting fixes.'
              branch: format-fix
              delete-branch: true
              base: main

  build-and-test:
    name: Build and Test
    needs: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
   
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
